/// Generated by AssetsRefGenerator on 2021/08/24
class Res {
  static const String ic_cource = "assets/images/ic_cource.svg";
  static const String ic_fail = "assets/images/ic_fail.svg";
  static const String ic_logo = "assets/images/ic_logo.svg";
  static const String ic_play = "assets/images/ic_play.svg";
  static const String ic_resume = "assets/images/ic_resume.svg";
  static const String ic_share = "assets/images/ic_share.svg";
  static const String ic_star_gray = "assets/images/ic_star_gray.svg";
  static const String ic_star_yelow = "assets/images/ic_star_yelow.svg";
  static const String ic_tick = "assets/images/ic_tick.svg";
  static const String ic_turtle = "assets/images/ic_turtle.svg";
  static const String image_background = "assets/images/image_background.png";
  static const String image_background2 = "assets/images/image_background2.png";
  static const String temp = "assets/images/temp.jpg";
  static const String en = "assets/locales/en.json";
  static const String vi = "assets/locales/vi.json";
}
